services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: podfront-ui
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    restart: unless-stopped
