FROM oven/bun:latest

# Set working directory
WORKDIR /app

# Copy package.json and bun.lock
COPY package.json bun.lock ./

# Install dependencies
RUN bun install

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 5173

# Set the command to run the application in development mode with hot reloading
CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
